
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://luvjqojwjtxjvgxfjqws.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx1dmpxb2p3anR4anZneGZqcXdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MTA4MDAsImV4cCI6MjA2NTM4NjgwMH0.VEQ0f6fJWBGwWZk2hL3-FsD6FmYwdBY_hRlx1JI9KJI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
